# Generated by Django 5.1.7 on 2025-04-24 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_face', '0003_remove_userprofile_image_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
